profit <- read.csv(file.choose())
View(profit)
table(profit$State)
str(profit)
profit$State <- as.numeric(profit$State)
summary(profit)
var(profit$R.D.Spend)
sd(profit$R.D.Spend)
var(profit$Administration)
var(profit$Marketing.Spend)
sd(profit$Marketing.Spend)
library(e1071)
skewness(profit$R.D.Spend)
skewness(profit$Administration)
skewness(profit$Marketing.Spend)
skewness(profit$Profit)
skewness(profit$State)
library(ggplot2)
r1 <- ggplot(profit,aes(profit$R.D.Spend))+geom_histogram(color="black",fill="red")
r2 <- ggplot(profit,aes(profit$R.D.Spend))+geom_boxplot(color="black",fill="red")+coord_flip()
a1 <- ggplot(profit,aes(profit$Administration))+geom_histogram(fill="blue",color="black")
a2 <- ggplot(profit,aes(profit$Administration))+geom_boxplot(fill="blue",color="black")+coord_flip()
p1 <- ggplot(profit,aes(profit$Profit))+geom_histogram(fill="green",color="black")
p2 <- ggplot(profit,aes(profit$Profit))+geom_boxplot(fill="green",color="black")+coord_flip()
s1 <- ggplot(profit,aes(profit$State))+geom_histogram(fill="purple",color="black")
s2 <- ggplot(profit,aes(profit$State))+geom_boxplot(fill="purple",color="black")+coord_flip()
library(gridExtra)
grid.arrange(r1,r2,a1,a2,p1,p2,s1,s2,nrow=4,ncol=2)
#checking for corelation
pairs(profit)
cor(profit$R.D.Spend,profit$Marketing.Spend)
cor(profit$R.D.Spend,profit$Profit)
#It shows that profit$R.D.Spend is a good variable for regression analysis
cor(profit$Marketing.Spend,profit$Profit)
cor(profit)
library(corpcor)
cor2pcor(cor(profit))
#checking the variable importance in grnerating the regression model
library(tree)
mod <- tree(profit$Profit~.,data=profit)
plot(mod)
text(mod)
library(randomForest)
mo <- randomForest(profit$Profit~.,data=profit)
varImpPlot(mo)
#creating a lm model
model1 <- lm(profit$Profit~profit$R.D.Spend)
summary(model1)
model2 <- lm(profit$Profit~profit$R.D.Spend+profit$Marketing.Spend+profit$Administration,data=profit)
summary(model2)
model3 <- lm(profit$Profit~.,data=profit)
summary(model3)
anova(model1,model2,model3)
#model2 is the most significant
predict(model2,interval="confidence")
confint(model2)
par(mfrow=c(2,2))
plot(model2)
