price <- read.csv(file.choose())
price <- price[,-1]
View(price)
str(price)
summary(price)
# cd,multi,premium are factor with categorical variable
price$cd <- as.numeric(price$cd)
price$multi <- as.numeric(price$multi)
price$premium <- as.numeric(price$premium)
attach(price)
a <- c(price$price,price$speed,price$hd,price$ram,price$ram,price$screen,price$screen,price$cd,price$multi,price$multi,price$premium,price$ads,price$trend)
var(price$price)
var(hd)
var(speed)
var(ram)
var(screen)
var(cd)
var(multi)
var(premium)
var(trend)
sd(price$price)
sd(hd)
sd(speed)
sd(ram)
sd(screen)
sd(cd)
sd(multi)
sd(premium)
sd(trend)
skewness(price$price)
skewness(hd)
skewness(speed)
skewness(ram)
skewness(screen)
skewness(cd)
skewness(multi)
skewness(premium)#premium is -vely skewed
skewness(trend)
library(ggplot2)
(p1 <-(ggplot(price,aes(price))+geom_histogram(color="black",fill="red")))
(p2 <- ggplot(price,aes(price))+geom_boxplot(color="black",fill="red")+coord_flip())
(h1 <- ggplot(price,aes(speed))+geom_histogram(color="black",fill="blue"))
(h2 <- ggplot(price,aes(speed))+geom_boxplot(fill="blue",color="black")+coord_flip())
(s1 <- ggplot(price,aes(ram))+geom_histogram(fill="green",color="black"))
(s2 <- ggplot(price,aes(ram))+geom_boxplot(fill="green",color="black")+coord_flip())
(a1 <- ggplot(price,aes(hd))+geom_histogram(fill="purple",color="black"))
(a2 <- ggplot(price,aes(hd))+geom_boxplot(fill="purple",color="black")+coord_flip())
(c1 <- ggplot(price,aes(screen))+geom_histogram(fill="yellow",color="black"))
(c2 <- ggplot(price,aes(screen))+geom_boxplot(fill="yellow",color="black")+coord_flip())
(d1 <- ggplot(price,aes(ads))+geom_histogram(fill="pink",color="black"))
(d2 <- ggplot(price,aes(ads))+geom_boxplot(fill="pink",color="black")+coord_flip())
library(gridExtra)
grid.arrange(p1,p2,h1,h2,s1,s2,a1,a2,c1,c2,d1,d2,nrow=6,ncol=2)
#check for corelation
pairs(price)
cor(price)
library(corpcor)
co2pcor(cor(price))
library(tree)
imp <- tree(price~.,data=price)
plot(imp)
text(imp)
library(randomForest)
im <- randomForest(price~.,data=price)
varImpPlot(im)
#Genererating the regression model
model1 <- lm(price~ram+hd+trend+speed+screen+premium,data=price)
summary(model1)
model2 <- lm(price~ram+hd+trend+screen+speed+premium+ads+cd,data=price)
summary(model2)
model3 <- lm(price~.,data=price)
summary(model3)
#model3 generate the most significant model
anova(model1,model2,model3)
predict(model3,interval="confidence")
confint(model3)
par(mfrow=c(2,2))
plot(model3)
library(mvinfluence)
influenceIndexPlot(model3)
model4 <- lm(price~.,data=price[c(-1441-1701),])
summary(model4)
